
# GEM DROP SECTION
# - SOUNDS: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# - PARTICLES: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# - ITEMS: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

drops:
  gems-per-day-per-player: 0 # set to 0 or lower to disable. if enabled, players will get fewer gems when they are closer to reach the daily limit of gems
  player-placed-history-length: 16384    # use lower if you don't have that much ram
  disabled_worlds:
    - lobby
  near-pickup: true # pickup items with full inventory if the drop is near the player
  near-pickup-particle-enabled: true # spawns a particle on the dropped gem when the player inv is full and near-pickup is enabled
  near-pickup-particle: SMALL_SMOKE
  gem: EMERALD
  condense-from: 8 # from this number and above, gems with this value will appear with the large material item
  large: EMERALD_BLOCK
  particle-enabled: true
  particle: CLOUD
  sound-enabled: true
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  glow-duration: 10 # seconds (set 0 to disable)

# ALWAYS USE MATERIAL NAMES ACCORDING TO YOUR MINECRAFT SERVER API.
# THIS LIST IS UPDATED TO 1.18. UPDATED LIST:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

blocks:
  COPPER_ORE:
    min: 0
    max: 1
  DEEPSLATE_COPPER_ORE:
    min: 0
    max: 1
  COAL_ORE:
    min: -1
    max: 1
  DEEPSLATE_COAL_ORE:
    min: -1
    max: 1
  DIAMOND_ORE:
    min: 1
    max: 5
  DEEPSLATE_DIAMOND_ORE:
    min: 1
    max: 4
  EMERALD_ORE:
    min: 1
    max: 4
  DEEPSLATE_EMERALD_ORE:
    min: 1
    max: 4
  GOLD_ORE:
    min: 0
    max: 1
  DEEPSLATE_GOLD_ORE:
    min: 0
    max: 1
  IRON_ORE:
    min: 0
    max: 1
  DEEPSLATE_IRON_ORE:
    min: 0
    max: 1
  LAPIS_ORE:
    min: 1
    max: 3
  DEEPSLATE_LAPIS_ORE:
    min: 1
    max: 3
  NETHER_QUARTZ_ORE:
    min: 1
    max: 2
  REDSTONE_ORE:
    min: 0
    max: 1
  DEEPSLATE_REDSTONE_ORE:
    min: 0
    max: 1
  JUNGLE_LOG:
    min: -3
    max: 1
  OAK_LOG:
    min: -3
    max: 1
  SPRUCE_LOG:
    min: -3
    max: 1
  ACACIA_LOG:
    min: -3
    max: 1
  BIRCH_LOG:
    min: -3
    max: 1
  DARK_OAK_LOG:
    min: -3
    max: 1
  MELON:
    min: 0
    max: 1
  PUMPKIN:
    min: 0
    max: 1

# ALWAYS USE ENTITY NAMES ACCORDING TO YOUR MINECRAFT SERVER API.
# THIS LIST IS UPDATED TO 1.15. UPDATED LIST:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

mobs:
  CAVE_SPIDER:
    min: 2
    max: 6
  ENDER_DRAGON:
    min: 12
    max: 21
  SPIDER:
    min: 2
    max: 5
  CREEPER:
    min: 2
    max: 5
  ZOMBIE:
    min: 2
    max: 4
  DROWNED:
    min: 2
    max: 4
  BLAZE:
    min: 3
    max: 10
  ELDER_GUARDIAN:
    min: 8
    max: 10
  ENDERMAN: # enable with caution, nerfed for player farms
    min: -1
    max: 0
  ENDERMITE:
    min: 2
    max: 5
  EVOKER:
    min: 5
    max: 9
  GHAST:
    min: 3
    max: 10
  HUSK:
    min: 1
    max: 3
  ILLUSIONER:
    min: 3
    max: 6
  PHANTOM:
    min: 2
    max: 5
  PILLAGER:
    min: 2
    max: 5
  RAVAGER:
    min: 4
    max: 9
  MAGMA_CUBE:
    min: 2
    max: 6
  SHULKER:
    min: 4
    max: 5
  SILVERFISH:
    min: 2
    max: 3
  SKELETON:
    min: 2
    max: 5
  SKELETON_HORSE:
    min: 3
    max: 7
  STRAY:
    min: 1
    max: 4
  VEX:
    min: 1
    max: 4
  VINDICATOR:
    min: 2
    max: 5
  WITCH:
    min: 3
    max: 5
  WITHER:
    min: 6
    max: 12
  WITHER_SKELETON:
    min: 3
    max: 6
  ZOMBIE_VILLAGER:
    min: 1
    max: 3

# ENTITY MATING WILL ALWAYS DROP THE SAME AMOUNT FOR ALL
# COMPATIBLE ENTITIES, BETWEEN THIS RANGE:

breeding:
  min: 1
  max: 3

# ALWAYS USE MATERIAL NAMES ACCORDING TO YOUR MINECRAFT SERVER API.
# THIS LIST IS UPDATED TO 1.15. UPDATED LIST:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# BLOCK DERIVABLE SUCH AS MELON OR PUMPKIN MUST GO INSIDE
# THE BLOCK LIST

farming:
  BEETROOT:
    seed: BEETROOT_SEEDS
    harvest:
      min: 0
      max: 1
    replant:
      min: 0
      max: 1
  WHEAT:
    seed: WHEAT_SEEDS
    harvest:
      min: 0
      max: 1
    replant:
      min: 0
      max: 1
  POTATOES:
    seed: POTATO
    harvest:
      min: 0
      max: 1
    replant:
      min: 0
      max: 1
  CARROTS:
    seed: CARROT
    harvest:
      min: 0
      max: 1
    replant:
      min: 0
      max: 1

# ECONOMY SECTION
# DEPENDENCIES -> Valut: https://github.com/MilkBowl/Vault, by MilkBowl.

economy:
  currency-color: "GREEN" # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
  currency: "◭" # currency for items when quantity > 1 and item is not condensed
  single-item-currency: "◬" # currency for items when quantity = 1 and item is not condensed
  currency-condensed: "▲" # currency for condensed items
  currency-before: true # [before]currency[!before]

  death:
    enable: true
    default: 15 # reminder: 15=15%.

    # if you want another % just set the permission to be gemmy.death.0-100 (without %).
    # for example, if you want players to drop 10% of their money, set gemmy.death.10
    # into their permission group.