main: co.purevanilla.mcplugins.gemmy.Main
author: quiquelhappy
api-version: 1.20
description: "Semi-item based economy"
version: 3.2.0
name: "Gemmy"
depend:
  - Vault
  - AFKPlus
  - Essentials
  - QuickShop-Hikari
commands:
  balancetop:
    aliases: [baltop]
    description: shows total points and balance top
  gemdrop:
    permission: "gemmy.gemdrop"
    aliases: ["drop"]
    usage: "/gemdrop <amount>"
    description: "drops specified amount"
  moneyrain:
    permission: "gemmy.moneyrain"
    aliases: ["mr"]
    usage: "/moneyrain"
    description: "starts a money rain on yourself"
