main: co.purevanilla.mcplugins.gemmy.Main
author: quiquelhappy
api-version: 1.13
description: "Semi-item based economy"
version: 2.4.0
name: "Gemmy"
depend: ["Vault"]
commands:
  gemdrop:
    permission: "gemmy.gemdrop"
    aliases: ["drop"]
    usage: "/gemdrop <amount>"
    description: "drops specified amount"
  moneyrain:
    permission: "gemmy.moneyrain"
    aliases: ["mr"]
    usage: "/moneyrain"
    description: "starts a money rain on yourself"
