name: Gemmy
version: 2.2
main: ovh.quiquelhappy.mcplugins.gemmy.main
description: Gem based economy helper
commands:
  burst:
    description: Create a gem burst
    usage: /gemmy burst [player]
    permission: gemmy.burst
    permission-message: You don't have permission